/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PosCadastroRouteImport } from './routes/pos-cadastro'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndicacoesRouteImport } from './routes/indicacoes'
import { Route as IndicacaoConfirmacaoRouteImport } from './routes/indicacao-confirmacao'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfirmacaoCadastroRouteImport } from './routes/confirmacao-cadastro'
import { Route as ConfirmacaoRouteImport } from './routes/confirmacao'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const PosCadastroRoute = PosCadastroRouteImport.update({
  id: '/pos-cadastro',
  path: '/pos-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicacoesRoute = IndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicacaoConfirmacaoRoute = IndicacaoConfirmacaoRouteImport.update({
  id: '/indicacao-confirmacao',
  path: '/indicacao-confirmacao',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacaoCadastroRoute = ConfirmacaoCadastroRouteImport.update({
  id: '/confirmacao-cadastro',
  path: '/confirmacao-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacaoRoute = ConfirmacaoRouteImport.update({
  id: '/confirmacao',
  path: '/confirmacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/confirmacao-cadastro': typeof ConfirmacaoCadastroRoute
  '/dashboard': typeof DashboardRoute
  '/indicacao-confirmacao': typeof IndicacaoConfirmacaoRoute
  '/indicacoes': typeof IndicacoesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/pos-cadastro': typeof PosCadastroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/confirmacao-cadastro': typeof ConfirmacaoCadastroRoute
  '/dashboard': typeof DashboardRoute
  '/indicacao-confirmacao': typeof IndicacaoConfirmacaoRoute
  '/indicacoes': typeof IndicacoesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/pos-cadastro': typeof PosCadastroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/confirmacao-cadastro': typeof ConfirmacaoCadastroRoute
  '/dashboard': typeof DashboardRoute
  '/indicacao-confirmacao': typeof IndicacaoConfirmacaoRoute
  '/indicacoes': typeof IndicacoesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/pos-cadastro': typeof PosCadastroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/confirmacao'
    | '/confirmacao-cadastro'
    | '/dashboard'
    | '/indicacao-confirmacao'
    | '/indicacoes'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/pos-cadastro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/confirmacao'
    | '/confirmacao-cadastro'
    | '/dashboard'
    | '/indicacao-confirmacao'
    | '/indicacoes'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/pos-cadastro'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/confirmacao'
    | '/confirmacao-cadastro'
    | '/dashboard'
    | '/indicacao-confirmacao'
    | '/indicacoes'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/pos-cadastro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CadastroRoute: typeof CadastroRoute
  ConfirmacaoRoute: typeof ConfirmacaoRoute
  ConfirmacaoCadastroRoute: typeof ConfirmacaoCadastroRoute
  DashboardRoute: typeof DashboardRoute
  IndicacaoConfirmacaoRoute: typeof IndicacaoConfirmacaoRoute
  IndicacoesRoute: typeof IndicacoesRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  PosCadastroRoute: typeof PosCadastroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pos-cadastro': {
      id: '/pos-cadastro'
      path: '/pos-cadastro'
      fullPath: '/pos-cadastro'
      preLoaderRoute: typeof PosCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicacoes': {
      id: '/indicacoes'
      path: '/indicacoes'
      fullPath: '/indicacoes'
      preLoaderRoute: typeof IndicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicacao-confirmacao': {
      id: '/indicacao-confirmacao'
      path: '/indicacao-confirmacao'
      fullPath: '/indicacao-confirmacao'
      preLoaderRoute: typeof IndicacaoConfirmacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacao-cadastro': {
      id: '/confirmacao-cadastro'
      path: '/confirmacao-cadastro'
      fullPath: '/confirmacao-cadastro'
      preLoaderRoute: typeof ConfirmacaoCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacao': {
      id: '/confirmacao'
      path: '/confirmacao'
      fullPath: '/confirmacao'
      preLoaderRoute: typeof ConfirmacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CadastroRoute: CadastroRoute,
  ConfirmacaoRoute: ConfirmacaoRoute,
  ConfirmacaoCadastroRoute: ConfirmacaoCadastroRoute,
  DashboardRoute: DashboardRoute,
  IndicacaoConfirmacaoRoute: IndicacaoConfirmacaoRoute,
  IndicacoesRoute: IndicacoesRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  PosCadastroRoute: PosCadastroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
