/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PosCadastroRouteImport } from './routes/pos-cadastro'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfirmacaoRouteImport } from './routes/confirmacao'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'

const PosCadastroRoute = PosCadastroRouteImport.update({
  id: '/pos-cadastro',
  path: '/pos-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacaoRoute = ConfirmacaoRouteImport.update({
  id: '/confirmacao',
  path: '/confirmacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/dashboard': typeof DashboardRoute
  '/pos-cadastro': typeof PosCadastroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/dashboard': typeof DashboardRoute
  '/pos-cadastro': typeof PosCadastroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/confirmacao': typeof ConfirmacaoRoute
  '/dashboard': typeof DashboardRoute
  '/pos-cadastro': typeof PosCadastroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cadastro' | '/confirmacao' | '/dashboard' | '/pos-cadastro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cadastro' | '/confirmacao' | '/dashboard' | '/pos-cadastro'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/confirmacao'
    | '/dashboard'
    | '/pos-cadastro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ConfirmacaoRoute: typeof ConfirmacaoRoute
  DashboardRoute: typeof DashboardRoute
  PosCadastroRoute: typeof PosCadastroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pos-cadastro': {
      id: '/pos-cadastro'
      path: '/pos-cadastro'
      fullPath: '/pos-cadastro'
      preLoaderRoute: typeof PosCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacao': {
      id: '/confirmacao'
      path: '/confirmacao'
      fullPath: '/confirmacao'
      preLoaderRoute: typeof ConfirmacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ConfirmacaoRoute: ConfirmacaoRoute,
  DashboardRoute: DashboardRoute,
  PosCadastroRoute: PosCadastroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
